version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: backend:1.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
