spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: swtod.s.system@gmail.com
    password: lsuygglexlivuash
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mail:
  host: swtod.s.system@gmail.com
